---
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

  # Import sorting
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript

  # prettier/recommended disables any eslint rules that could conflict
  - plugin:prettier/recommended
  - prettier/react
  - prettier/@typescript-eslint

plugins:
  - react
  - '@typescript-eslint'
  - import
  - prettier

env:
  browser: true
  jasmine: true
  jest: true

rules:
  # Formatting
  # See also .prettierrc.yml and .editorconfig
  prettier/prettier: warn
  import/order:
    - warn
    - newlines-between: always
      groups:
        - builtin
        - external
        - parent
        - sibling
        - index
  # Code quality
  '@typescript-eslint/no-non-null-assertion': off

settings:
  react:
    pragma: React
    version: detect

parser: '@typescript-eslint/parser'

ignorePatterns:
  - node_modules/
  - out
  - '.next'
