---
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

  # Import sorting
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript

  # prettier/recommended disables any eslint rules that could conflict
  - plugin:prettier/recommended
  - prettier/react
  - prettier/@typescript-eslint

plugins:
  - react
  - '@typescript-eslint'
  - import
  - prettier

env:
  browser: true
  jasmine: true
  jest: true

rules:
  # Formatting
  # See also .prettierrc.yml and .editorconfig
  prettier/prettier: warn
  import/first: warn
  import/newline-after-import: warn
  import/order:
    - warn
    - newlines-between: always
      groups:
        - builtin
        - external
        - parent
        - sibling
        - index
  # Code quality
  '@typescript-eslint/no-non-null-assertion': off
  import/no-unresolved: error
  import/no-named-as-default-member: warn
  import/default: off # does not interpret module.exports = ... as a default export, so React false-positives
  import/group-exports: warn
  import/prefer-default-export: warn

settings:
  react:
    pragma: React
    version: detect
  import/parsers:
    '@typescript-eslint/parser': [.ts, .tsx]
  import/resolver:
    typescript:
      alwaysTryTypes: true

parser: '@typescript-eslint/parser'

ignorePatterns:
  - node_modules/
  - out
  - '.next'
